language: php

php:
- 7.0
- hhvm

matrix:
  allow_failures:
  - php: hhvm

sudo: false

before_install:
- travis_retry composer self-update

install:
- composer install -o

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b1c428c4ec675b45dd8c
    on_success: change
    on_failure: always
    on_start: never
