language: php

dist: trusty
sudo: false

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- nightly
- hhvm

matrix:
  allow_failures:
  - php: nightly
  - php: hhvm
  fast_finish: true
  include:
  - php: 5.3
    dist: precise

before_install:
- travis_retry composer self-update

install:
- flags="--ansi --prefer-dist --optimize-autoloader --no-interaction --no-progress --no-suggest"
- composer install $flags

script:
- ./vendor/bin/phpunit

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b1c428c4ec675b45dd8c
    on_success: change
    on_failure: always
    on_start:   never
